// Re-export all data methods from the REST API
export {
  getAllProjects,
  getProjectByCategory,
  insertProject,
  updateProject,
  deleteProject,
  getAllSkills,
  getSkillsByCategory,
  insertSkill,
  updateSkill,
  deleteSkill,
  getAllExperiences,
  insertExperience,
  updateExperience,
  deleteExperience,
  getAboutMe,
  updateAboutMe,
  sendMessage,
  getAllMessages,
  markMessageAsRead,
  deleteMessage,
  uploadProjectImage,
  uploadProfileImage,
  getAllEducation,
  insertEducation,
  updateEducation,
  deleteEducation,
  getAllCertifications,
  insertCertification,
  updateCertification,
  deleteCertification,
} from './Api';
